# Generated by Django 4.2 on 2023-06-13 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion3', '0002_foro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('usuarioComent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion3.usuario')),
            ],
        ),
    ]
