# Generated by Django 4.2 on 2023-06-16 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion3', '0003_comentarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='foro',
            name='imagen',
            field=models.ImageField(blank=None, default=0, upload_to='static/imagenes/foro'),
            preserve_default=False,
        ),
    ]
