# Generated by Django 4.2 on 2023-06-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion3', '0004_foro_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tematica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.ImageField(blank=None, upload_to='static/imagenes/foro')),
            ],
        ),
        migrations.RemoveField(
            model_name='foro',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='foro',
            name='usuarioForo',
        ),
    ]
