# Generated by Django 4.2 on 2023-07-07 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion3', '0006_algebra_geometria_numeros_probabilidad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sugerencias',
            old_name='usuarioComent',
            new_name='usuarioSugerencia',
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(max_length=300)),
                ('usuarioComentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion3.usuario')),
            ],
        ),
    ]
