# Generated by Django 4.2 on 2023-07-07 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion3', '0007_rename_usuariocoment_sugerencias_usuariosugerencia_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comentario',
            new_name='Comentarios',
        ),
    ]
